name: learning_english
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.2.1
  font_awesome_flutter: ^10.7.0
  video_player: ^2.9.1
  youtube_player_flutter: ^9.0.1
  flutter_tts: ^3.8.5
  http: ^1.5.0
  supabase_flutter: ^2.10.2
  app_links: ^6.4.1
  google_sign_in: ^7.2.0
  shared_preferences: ^2.5.3

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:


  uses-material-design: true
  assets:
    - assets/logo_LearningEnglish.png
    - assets/default_avatar.png
    - assets/google_logo.png
